from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle
)

from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.enums import TA_CENTER


def generate_report(answers, report_text):

    pdf_file = "Interview_Report.pdf"

    doc = SimpleDocTemplate(pdf_file)

    styles = getSampleStyleSheet()

    title_style = styles["Title"]
    title_style.alignment = TA_CENTER

    heading = styles["Heading2"]
    body = styles["BodyText"]

    content = []

    # ----------------------------------------
    # TITLE
    # ----------------------------------------

    content.append(
        Paragraph(
            "🤖 AI SMART INTERVIEW REPORT",
            title_style
        )
    )

    content.append(Spacer(1, 20))

    # ----------------------------------------
    # SUMMARY TABLE
    # ----------------------------------------

    table_data = [

        ["Metric", "Result"],

        ["Overall Rating", "⭐⭐⭐⭐☆"],

        ["Confidence", "92%"],

        ["Technical Skills", "89%"],

        ["Communication", "91%"],

        ["Problem Solving", "86%"],

        ["Fluency", "90%"],

        ["Recommendation", "Highly Recommended"]

    ]

    table = Table(table_data, colWidths=[220,220])

    table.setStyle(

        TableStyle([

            ("BACKGROUND",(0,0),(-1,0),colors.darkblue),

            ("TEXTCOLOR",(0,0),(-1,0),colors.white),

            ("GRID",(0,0),(-1,-1),1,colors.grey),

            ("BACKGROUND",(0,1),(-1,-1),colors.beige),

            ("FONTNAME",(0,0),(-1,0),"Helvetica-Bold"),

            ("BOTTOMPADDING",(0,0),(-1,0),12),

            ("ALIGN",(0,0),(-1,-1),"CENTER")

        ])

    )

    content.append(table)

    content.append(Spacer(1,20))

    # ----------------------------------------
    # ANSWERS
    # ----------------------------------------

    content.append(
        Paragraph(
            "Interview Answers",
            heading
        )
    )

    content.append(Spacer(1,10))

    for i, ans in enumerate(answers):

        content.append(

            Paragraph(

                f"<b>Question {i+1}</b>",

                heading

            )

        )

        content.append(

            Paragraph(

                ans,

                body

            )

        )

        content.append(Spacer(1,12))

    # ----------------------------------------
    # AI REPORT
    # ----------------------------------------

    content.append(

        Paragraph(

            "AI Evaluation",

            heading

        )

    )

    content.append(

        Paragraph(

            report_text,

            body

        )

    )

    content.append(Spacer(1,20))

    # ----------------------------------------
    # STRENGTHS
    # ----------------------------------------

    content.append(

        Paragraph(

            "<b>Strengths</b>",

            heading

        )

    )

    content.append(

        Paragraph(

            """
            • Good Technical Knowledge<br/>
            • Clear Communication<br/>
            • Confident Answering<br/>
            • Strong Problem Solving
            """,

            body

        )

    )

    content.append(Spacer(1,20))

    # ----------------------------------------
    # IMPROVEMENTS
    # ----------------------------------------

    content.append(

        Paragraph(

            "<b>Areas for Improvement</b>",

            heading

        )

    )

    content.append(

        Paragraph(

            """
            • Give more real-world examples<br/>
            • Improve answer structure<br/>
            • Maintain eye contact during interviews<br/>
            • Reduce filler words
            """,

            body

        )

    )

    content.append(Spacer(1,30))

    # ----------------------------------------
    # FOOTER
    # ----------------------------------------

    content.append(

        Paragraph(

            "<b>Generated by AI Smart Interview Guide</b>",

            title_style

        )

    )

    doc.build(content)

    return pdf_file